spring:
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: none
    # 30 天过期
    timeout: 86400
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudbridgeapi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      connect-timeout: 1000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    loadbalancer:
      timeout:
        connect: 360000  # 连接超时，单位为毫秒
        read: 360000    # 读取超时，单位为毫秒
    sentinel:
      eager: true # 是否饥饿加载。默认为 false 关闭
      filter:
        url-patterns: /**
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
      web-context-unify: false # controller层的方法对service层调用不认为是同一个根链路
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            namespace: 1f0ffb92-39a2-4efc-9c97-a31130a189d1
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # com.alibaba.cloud.sentinel.datasource.RuleType
server:
  address: 0.0.0.0
  port: 7529
  tomcat:
    connection-timeout: 360000  # 超时设置
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


cloudbridge:
  client:
    GATEWAY_HOST: http://localhost:8090
    access-key: zs
    secret-key: 123456

dubbo:
  application:
    name: CloudBridge-Backend
    logger: slf4j
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
logging:
  level:
    root: warn

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zs.project
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

sdk:
  path: D:\Data\SDK\